package com.bbkmobile.iqoo.console.dao.review;

// Generated 2012-1-5 17:13:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.bbkmobile.iqoo.console.dao.appinfo.AppInfo;
import com.bbkmobile.iqoo.console.dao.login.BbkAdminUser;

/**
 * ReviewRecords generated by hbm2java
 */
public class ReviewRecords implements java.io.Serializable {

	private static final long serialVersionUID = 4068655082678001370L;
	private Long id;
	private BbkAdminUser reviewUser;
	private AppInfo appInfo;
	private char reviewStatus;
	private String reviewOpinion;
	private Date reviewDate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BbkAdminUser getReviewUser() {
		return reviewUser;
	}

	public void setReviewUser(BbkAdminUser reviewUser) {
		this.reviewUser = reviewUser;
	}

	public AppInfo getAppInfo() {
		return appInfo;
	}

	public void setAppInfo(AppInfo appInfo) {
		this.appInfo = appInfo;
	}

	public char getReviewStatus() {
		return this.reviewStatus;
	}

	public void setReviewStatus(char reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

	public String getReviewOpinion() {
		return this.reviewOpinion;
	}

	public void setReviewOpinion(String reviewOpinion) {
		this.reviewOpinion = reviewOpinion;
	}

	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}
}
