package com.bbkmobile.iqoo.console.dao.appinfo;

// Generated 2012-1-9 9:11:11 by Hibernate Tools 3.4.0.CR1

/**
 * TAppPermission generated by hbm2java
 */
public class TAppPermission implements java.io.Serializable {

	private Long id;
	private AppInfo appInfo;
	private String permission;


	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AppInfo getAppInfo() {
		return this.appInfo;
	}

	public void setAppInfo(AppInfo appInfo) {
		this.appInfo = appInfo;
	}

	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

}
