package com.bbkmobile.iqoo.console.dao.apptype;

import java.io.File;
import java.util.Set;

//import org.apache.catalina.util.InstanceSupport;

// Generated 2011-12-28 16:55:06 by Hibernate Tools 3.4.0.CR1

/**
 * AppType generated by hbm2java
 */
@SuppressWarnings("serial")
public class AppType implements java.io.Serializable {

	private Integer id;
	private AppType parentType;
	private String typeName;
	private String typeEnName;
	private String typeIcon;
	private int typeOrder;
	private String typeDesc;
	private char typeStatus;
	private Set<AppType> childAppTypes;

	private File icon;
	private String iconFileName;
	private String iconContentType;
	private Integer parentId;

	private Integer index = 0;
	private Integer ref_sortorder = 0;
	
	private String appCnNames;

	public AppType() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getTypeIcon() {
		return this.typeIcon;
	}

	public void setTypeIcon(String typeIcon) {
		this.typeIcon = typeIcon;
	}

	public int getTypeOrder() {
		return this.typeOrder;
	}

	public void setTypeOrder(int typeOrder) {
		this.typeOrder = typeOrder;
	}

	public String getTypeDesc() {
		return this.typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	public char getTypeStatus() {
		return this.typeStatus;
	}

	public void setTypeStatus(char typeStatus) {
		this.typeStatus = typeStatus;
	}

	public AppType getParentType() {
		return parentType;
	}

	public void setParentType(AppType parentType) {
		this.parentType = parentType;
	}

	public Set<AppType> getChildAppTypes() {
		return childAppTypes;
	}

	public void setChildAppTypes(Set<AppType> childAppTypes) {
		this.childAppTypes = childAppTypes;
	}

	public File getIcon() {
		return icon;
	}

	public void setIcon(File icon) {
		this.icon = icon;
	}

	public String getIconFileName() {
		return iconFileName;
	}

	public void setIconFileName(String iconFileName) {
		this.iconFileName = iconFileName;
	}

	public String getIconContentType() {
		return iconContentType;
	}

	public void setIconContentType(String iconContentType) {
		this.iconContentType = iconContentType;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getIndex() {
		return index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	public Integer getRef_sortorder() {
		return ref_sortorder;
	}

	public void setRef_sortorder(Integer ref_sortorder) {
        this.ref_sortorder = ref_sortorder;
    }

    public String getTypeEnName() {
        return this.typeEnName;
    }

    public void setTypeEnName(String typeEnName) {
        this.typeEnName = typeEnName;
    }

    public String getAppCnNames() {
        return this.appCnNames;
    }

    public void setAppCnNames(String appCnNames) {
        this.appCnNames = appCnNames;
    }

	@Override
	public boolean equals(Object target) {
		if (target instanceof AppType) {
			if (null != target) {
				AppType temp = (AppType) target;
				if (null != this.id) {
					if (this.id.equals(temp.getId())) {
						return true;
					}
				}
			}
		}
		return false;
	}
}
